### ISSUE TITLE
setting to change the color

### ISSUE THREAD

**Issue by dalexj** [wpillar/atom-trailing-spaces#14]

**Comment by cardoni** [comment]
Have you tried editing your atom stylesheet ( in `~/.atom/styles.less`) and changing the highlight color?

Something like this should get you close:
```css
.trailing-whitespace {
    background: rgba(79, 153, 211, 0.25);
    border-radius: 2px;
}
```
