### ISSUE TITLE
Seeing no highlight whatsoever

### ISSUE THREAD

**Issue by elisee** [wpillar/atom-trailing-spaces#16]
The latest `trailing-spaces.atom-text-editor.less` stylesheet  doesn't seem to highlight any trailing spaces at all, at least when both settings are enabled. Reverting back to just:

```less
.trailing-whitespace {
  background: #4182c4;
  border-radius: 2px;
}
```

Fixes it, so it's most likely a stylesheet issue? I'm using the One Dark theme.
