### ISSUE TITLE
Cannot remove indication on blank lines.

### ISSUE THREAD

**Issue by xaxazak** [wpillar/atom-trailing-spaces#25]
Regardless of the state of "Enable For Indentation", lines consisting purely of tabs or spaces are being highlighted.

The "Enable for Cursor Lines" option works correctly AFAICT.

Atom: 1.12.5
Trailing Spaces: 0.3.2
Linux (Xubuntu 16.10)

**Comment by mignz** [comment]
I have tried the extension today and have the same issue. Unlike Sublime's trailing-spaces, it still considers as whitespace the idented lines with no text.

So I've digged for a while and found a solution, not using this extension but adding this to Atom's stylesheet (Atom -> Stylesheet...):

```css
atom-text-editor {
    .line {
        .trailing-whitespace {
            background: @background-color-warning;
            border-radius: 2px;
        }
        
        &.cursor-line {
            .trailing-whitespace {
                background: none;
            }
        }
        
        span > .trailing-whitespace:first-child:nth-last-child(1) {
            background: none;
        }
        
        span > .invisible-character.trailing-whitespace:first-child:nth-last-child(2) {
            background: none;
        }
    }
}
```

So it looks for a span in a line where there's only one .trailing-whitespace. Haven't given it much of a test but it should work everywhere.
